baseURL = "https://nomaad.github.io/"
title = "Matthias Zaugg"
pagination.pagerSize = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
enableEmoji = true
defaultContentLanguage = "de"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Matthias Zaugg"
description = "Portfolio von Matthias Zaugg, Soziologe mit Software-Hintergrund | Data Analyst | Digitalisierung, (Ent-)Demokratisierung & Gesellschaftstheorie | R, TypeScript, C#, Python | Wien, Bern"
keywords = [ "Blog", "Portfolio"]
author = "Matthias Zaugg"
#images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "2. January 2006"
defaultTheme = "light"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  #favicon = "<link / abs url>"
  #favicon16x16 = "<link / abs url>"
  #favicon32x32 = "<link / abs url>"
  #apple_touch_icon = "<link / abs url>"
  #safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Matthias Zaugg"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Matthias Zaugg"
  subtitle = "Soziologe mit Software-Hintergrund | Data Analyst | Digitalisierung, (Ent-)Demokratisierung & Gesellschaftstheorie | R, TypeScript, C#, Python | Wien, Bern"
  imageUrl = "/img/mz.png"
  imageWidth = 150
  imageHeight = 150
  imageTitle = "Matthias Zaugg"

    #[[params.profileMode.buttons]]
    #name = "Blog"
    #url = "posts"

    #[[params.profileMode.buttons]]
    #name = "Themen"
    #url = "tags"

  [params.homeInfoParams]
  Title = "Matthias Zaugg"
  Content = "Soziologe mit Software-Hintergrund | Data Analyst | Digitalisierung, (Ent-)Demokratisierung & Gesellschaftstheorie | R, TypeScript, C#, Python | Wien, Bern"
  
  [[params.socialIcons]]
  name = "bluesky"
  url = "https://bsky.app/profile/matthiaszaugg.bsky.social"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nomaad/"

[params.analytics.google]
SiteVerificationTag = "G-WE9N8RLG8G"

[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
#SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  #[params.editPost]
  #URL = "https://github.com/<path_to_repo>/content"
  #Text = "Suggest Changes"
  #appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "categories"
#name = "Kategorien"
#url = "/categories/"
#weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Themen"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "Über mich"
url = "/about/"
weight = 30

[[menu.main]]
identifier = "search"
name = "Suche"
url = "/search/"
weight = 90

#[[menu.main]]
#identifier = "example"
#name = "example.org"
#url = "https://example.org"
#weight = 30

[markup.highlight]
noClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
