---
title: "Parlament.ch"
author: "Matthias Zaugg"
date: "13 12 2020"
output: html_document
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Daten einlesen

```{r}
library(tidyverse)
library(quanteda)

filenames <- list.files(path="~/Documents/Coding/Datasets/Corpora/parlament.ch/", pattern="*.csv", full.names=T, recursive=F)
df = data.frame()
for(file in filenames){
  df <- rbind(df, read.csv(file))
}

#df <- read.csv("~/Desktop/parlch_50.csv")
head(df)

# Nur mündliche Voten in Deutsch berücksichtigen
df <- df %>% filter(vote.type=="oral", vote.language=="german")

# Corups erstellen
corpus <- corpus(df, text_field = "vote.text")
docvars(corpus)

# keywords in context
kwic <- kwic(corpus, "Dividenden")
head(kwic)
```

## DFM erstellen

```{r}
dfm <- dfm(corpus,
           stem = F,
           tolower=T,
           remove = c(stopwords("german"), letters, c("dass", "müssen")),
           what = "word",
           remove_punct = T,
           remove_symbols = T,
           remove_numbers = T,
           remove_url = T,
           remove_separators = T)

# Die 20 häufigsten Wörter?
freq <- textstat_frequency(dfm, n = 20)
ggplot(freq, aes(x = reorder(feature, frequency), y = frequency)) + 
  geom_point() +
  coord_flip() +
  labs(x = NULL, y = "Anzahl Verwendungen", title = "Häufigste Wörter in den bisherigen Debatten der 50. Legislatur") +
  theme_bw()

# Welche Wörter verwendet Mattea Meyer?
textplot_wordcloud(dfm_subset(dfm, councilor.name=="Meyer Mattea"), min.freq=10, random.order = FALSE, rot.per = .25, colors = RColorBrewer::brewer.pal(8,"Dark2"))

# Und Ueli Maurer so?
textplot_wordcloud(dfm_subset(dfm, councilor.name=="Maurer Ueli"), min.freq=20, random.order = FALSE, rot.per = .25, colors = RColorBrewer::brewer.pal(8,"Dark2"))

# Cedric Wermuth?
textplot_wordcloud(dfm_subset(dfm, councilor.name=="Wermuth Cédric"), min.freq=5, random.order = FALSE, rot.per = .25, colors = RColorBrewer::brewer.pal(8,"Dark2"))

```





## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
