---
title: "Linkage Politics and Complex Governance in Transatlantic Surveillance "
subtitle: "By Henry Farrell and Abraham L. Newman"
#author: "Yihui Xie"
#institute: "RStudio, PBC"
date: "10.06.2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse, center, middle

# Theoretical framework
---

# Goal & Method

- Farrell and Newman aim to create a theory how linkage politics change or alter the influence of state actors and private actors on an international level

- They use international cooperation over intelligence, surveillance and privacy matters in transatlantic relationships as empirical example for their theory

---

# Argument

Their argument is that actors use issue linkage to exploit a plurality of opportunity structures. Meaning that Farrell and Newman investigate how private and state actors use domestic rule-setting structures to influence international negotiations.

---

# Argument

- Private actors are bargainers in international negotiations

- Greater economic exchange and increased international communication has undermined states’ monopoly control over many channels of diplomacy

- Newman and Farrell put a focus on how differences in domestic structures allow different actors to use issue linkage to influence international bargaining processes.

---

# Issue Linkage

- *Issue Linkage* = an actor A who has a strong influence on a certain issue but is weak in another will try to keep these two fields separated and focus on the field the actor is strong in. An actor B who may have strong competences in the second field but not in the first will try to connect both issues to strengthen his position, when initially only issue A was negotiated.

- New knowledge may allow an actor to link two fields that before seemed unrelated.

---

# Hypotheses

Farrell and Newman formulate two hypotheses regarding actors behavior towards issue linkage:

- *H1:* When issue linkage potentially conjoin one policy area to another in which a given actor has less access to political opportunity structures, that actor will seek to keep issue areas separate to avoid a loss of influences. 

- *H2:* When the salient policy is located in an issue area in which a given actor has less access to opportunity structures and it is possible to join the salient policy together with an issue area in which that actor has more access, the actor will seek to join issue areas together and to exploit the relevant opportunity structures to gain influence over the negotiation outcome.

---

class: inverse, center, middle

# Empirical evidence

---
# Transatlantic data transfer

Three phases:

1. Commercialization of the Internet (1990s)

2. After 9/11 

3. Snowden Affair Knowledge Shock (2013 onward)

---

# First phase: Safe Harbor

- Information sharing as issue of trade

- First US-EU disputes -> *Safe Harbor* agreement 1998

- Dissent from nonstate actors but lack of decision making structures

- EU & US defend *Safe Harbor*

---

# Second phase: After 9/11

- US ask EU to engage in information exchange to fight terrorism

- Data transfer now framed in terms of national security

- Officials seek to keep issue separate from *Safe Harbor* debate

---

# Third phase: Snowden Affair as "knowledge shock"

- EC admits that Safe Harbor has flaws

- Issue linkage: data transfer as issue of commerce AND security

- New leverage potential through linkage (due to better decision making structure for security issue)

- Schrems case 2014: activist lawyer against Facebook

- ECJ 2015: Safe Harbor does not protect privacy of EU citizens sufficiently

---

# Present situation?

- 2016 *Privacy Shield* as successor of *Safe Harbor*

- Schrems II 2018: *Privacy Shield* still has flaws

- ECJ 2020: affirms Schrems' claim -> *Privacy Shield* invalidated

- Several actors pushing for domestic reform within US

- Biden visits Brussels: New debates on third agreement starting June 15th?

---

class: center, middle

# Thanks!
